package fuzzyfrenagem;

import net.sourceforge.jFuzzyLogic.FIS;
import net.sourceforge.jFuzzyLogic.plot.JDialogFis;
import net.sourceforge.jFuzzyLogic.rule.Variable;

public class FrmJFuzzyLogic extends javax.swing.JFrame {

    double sensorDistancia;
    double sensorVelocidade;
    
    // Parametros do sistema Fuzzy
    String fileName = "regras.fcl";
    FIS fis = FIS.load(fileName);
    JDialogFis dialog = new JDialogFis(fis);
            
    public FrmJFuzzyLogic() {
        initComponents();
    }
    
    void fuzzifica(){
        fis.setVariable("Distancia", sensorDistancia);
        fis.setVariable("Velocidade", sensorVelocidade);
        fis.evaluate();
        Variable resp = fis.getVariable("pressao");
        Double saida = resp.getValue();
        jLabelpressao.setText(String.valueOf(saida));
        
        dialog.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderDistancia = new javax.swing.JSlider();
        jSliderVelocidade = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelDistancia = new javax.swing.JLabel();
        jLabelVelocidade = new javax.swing.JLabel();
        jLabelpressao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Frenagem");
        setMinimumSize(new java.awt.Dimension(825, 450));
        getContentPane().setLayout(null);

        jSliderDistancia.setMaximum(30);
        jSliderDistancia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderDistanciaStateChanged(evt);
            }
        });
        getContentPane().add(jSliderDistancia);
        jSliderDistancia.setBounds(397, 63, 200, 20);

        jSliderVelocidade.setMaximum(240);
        jSliderVelocidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVelocidadeStateChanged(evt);
            }
        });
        getContentPane().add(jSliderVelocidade);
        jSliderVelocidade.setBounds(400, 150, 200, 20);

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Distância");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 70, 90, 16);

        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Velocidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 150, 90, 16);

        jLabelDistancia.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDistancia.setText("*");
        getContentPane().add(jLabelDistancia);
        jLabelDistancia.setBounds(639, 67, 80, 16);

        jLabelVelocidade.setForeground(new java.awt.Color(255, 0, 51));
        jLabelVelocidade.setText("*");
        getContentPane().add(jLabelVelocidade);
        jLabelVelocidade.setBounds(639, 150, 110, 16);

        jLabelpressao.setForeground(new java.awt.Color(255, 0, 51));
        jLabelpressao.setText("*");
        getContentPane().add(jLabelpressao);
        jLabelpressao.setBounds(491, 206, 90, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzyfrenagem/Imagem/distancia-de-frenagem.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 820, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderDistanciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderDistanciaStateChanged
        sensorDistancia = jSliderDistancia.getValue();
        jLabelDistancia.setText(String.valueOf(sensorDistancia));
        fuzzifica();
    }//GEN-LAST:event_jSliderDistanciaStateChanged

    private void jSliderVelocidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVelocidadeStateChanged
        sensorVelocidade = jSliderVelocidade.getValue();
        jLabelVelocidade.setText(String.valueOf(sensorVelocidade));
        fuzzifica();
    }//GEN-LAST:event_jSliderVelocidadeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJFuzzyLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJFuzzyLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJFuzzyLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJFuzzyLogic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJFuzzyLogic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDistancia;
    private javax.swing.JLabel jLabelVelocidade;
    private javax.swing.JLabel jLabelpressao;
    private javax.swing.JSlider jSliderDistancia;
    private javax.swing.JSlider jSliderVelocidade;
    // End of variables declaration//GEN-END:variables
}
